### ISSUE TITLE
Could not read file 'mouse/</TITLE>.fa': No such file or directory

### ISSUE THREAD

**Issue by anksi** [olarerin/metaPlotR#3]
Hi,
For some reason, while creating master annotation, file "make_annot_bed.pl" does not recognize the genome directory and I can not guess what might have gone wrong! 

Can you please help me in detecting the same. Below I have provided the detailed command used and list of the tools installed in the environment.
Thanks in advance for your help.

**Command used and error:**

**perl make_annot_bed.pl --genomeDir mouse/ --genePred mm9_genePrid.txt**

Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 2.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 2.
Use of uninitialized value $chr in string ne at make_annot_bed.pl line 38, <ANNOT> line 2.
Use of uninitialized value $txStart in addition (+) at make_annot_bed.pl line 51, <ANNOT> line 2.
Use of uninitialized value $cdsStart in addition (+) at make_annot_bed.pl line 52, <ANNOT> line 2.
Use of uninitialized value $exonCount in numeric lt (<) at make_annot_bed.pl line 62, <ANNOT> line 2.
Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 3.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 3.
Use of uninitialized value $chr in string ne at make_annot_bed.pl line 38, <ANNOT> line 3.
Use of uninitialized value $txStart in addition (+) at make_annot_bed.pl line 51, <ANNOT> line 3.
Use of uninitialized value $cdsStart in addition (+) at make_annot_bed.pl line 52, <ANNOT> line 3.
Use of uninitialized value $exonCount in numeric lt (<) at make_annot_bed.pl line 62, <ANNOT> line 3.
Use of uninitialized value $temp[-1] in split at make_annot_bed.pl line 32, <ANNOT> line 4.
Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 4.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 4.
Use of uninitialized value $chr in string ne at make_annot_bed.pl line 38, <ANNOT> line 4.
Use of uninitialized value $txStart in addition (+) at make_annot_bed.pl line 51, <ANNOT> line 4.
Use of uninitialized value $cdsStart in addition (+) at make_annot_bed.pl line 52, <ANNOT> line 4.
Use of uninitialized value $exonCount in numeric lt (<) at make_annot_bed.pl line 62, <ANNOT> line 4.
Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 5.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 5.
Use of uninitialized value $chr in string ne at make_annot_bed.pl line 38, <ANNOT> line 5.
Use of uninitialized value $txStart in addition (+) at make_annot_bed.pl line 51, <ANNOT> line 5.
Use of uninitialized value $cdsStart in addition (+) at make_annot_bed.pl line 52, <ANNOT> line 5.
Use of uninitialized value $exonCount in numeric lt (<) at make_annot_bed.pl line 62, <ANNOT> line 5.
Use of uninitialized value $temp[-1] in split at make_annot_bed.pl line 32, <ANNOT> line 6.
Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 6.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 6.
Use of uninitialized value $chr in string ne at make_annot_bed.pl line 38, <ANNOT> line 6.
Use of uninitialized value $txStart in addition (+) at make_annot_bed.pl line 51, <ANNOT> line 6.
Use of uninitialized value $cdsStart in addition (+) at make_annot_bed.pl line 52, <ANNOT> line 6.
Use of uninitialized value $exonCount in numeric lt (<) at make_annot_bed.pl line 62, <ANNOT> line 6.
Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 7.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 7.
Use of uninitialized value $chr in string ne at make_annot_bed.pl line 38, <ANNOT> line 7.
Use of uninitialized value $txStart in addition (+) at make_annot_bed.pl line 51, <ANNOT> line 7.
Use of uninitialized value $cdsStart in addition (+) at make_annot_bed.pl line 52, <ANNOT> line 7.
Use of uninitialized value $exonCount in numeric lt (<) at make_annot_bed.pl line 62, <ANNOT> line 7.
Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 8.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 8.
Use of uninitialized value $chr in string ne at make_annot_bed.pl line 38, <ANNOT> line 8.
Use of uninitialized value $txStart in addition (+) at make_annot_bed.pl line 51, <ANNOT> line 8.
Use of uninitialized value $cdsStart in addition (+) at make_annot_bed.pl line 52, <ANNOT> line 8.
Use of uninitialized value $exonCount in numeric lt (<) at make_annot_bed.pl line 62, <ANNOT> line 8.
Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 9.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 9.
Use of uninitialized value $chr in string ne at make_annot_bed.pl line 38, <ANNOT> line 9.
Use of uninitialized value $txStart in addition (+) at make_annot_bed.pl line 51, <ANNOT> line 9.
Use of uninitialized value $cdsStart in addition (+) at make_annot_bed.pl line 52, <ANNOT> line 9.
Use of uninitialized value $exonCount in numeric lt (<) at make_annot_bed.pl line 62, <ANNOT> line 9.
Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 10.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 10.
Use of uninitialized value $chr in string ne at make_annot_bed.pl line 38, <ANNOT> line 10.
Use of uninitialized value $txStart in addition (+) at make_annot_bed.pl line 51, <ANNOT> line 10.
Use of uninitialized value $cdsStart in addition (+) at make_annot_bed.pl line 52, <ANNOT> line 10.
Use of uninitialized value $exonCount in numeric lt (<) at make_annot_bed.pl line 62, <ANNOT> line 10.
Use of uninitialized value $temp[9] in split at make_annot_bed.pl line 33, <ANNOT> line 11.
Use of uninitialized value $temp[10] in split at make_annot_bed.pl line 34, <ANNOT> line 11.

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file 'mouse//</TITLE>.fa': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /home/anksi/miniconda3/envs/data_viz/lib/site_perl/5.26.2/Bio/Root/Root.pm:447
STACK: Bio::Root::IO::_initialize_io /home/anksi/miniconda3/envs/data_viz/lib/site_perl/5.26.2/Bio/Root/IO.pm:268
STACK: Bio::SeqIO::_initialize /home/anksi/miniconda3/envs/data_viz/lib/site_perl/5.26.2/Bio/SeqIO.pm:513
STACK: Bio::SeqIO::fasta::_initialize /home/anksi/miniconda3/envs/data_viz/lib/site_perl/5.26.2/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /home/anksi/miniconda3/envs/data_viz/lib/site_perl/5.26.2/Bio/SeqIO.pm:389
STACK: Bio::SeqIO::new /home/anksi/miniconda3/envs/data_viz/lib/site_perl/5.26.2/Bio/SeqIO.pm:435
STACK: main::loadGenome make_annot_bed.pl:121
STACK: make_annot_bed.pl:39
-----------------------------------------------------------

**Environment details**
# packages in environment at data_viz:
#
# Name                    Version                   Build  Channel
atk                       2.8.0                         0    mw
bamtools                  2.5.1                he860b03_5    bioconda
bedtools                  2.29.2               hc088bd4_0    bioconda
biopython                 1.76             py38h7b6447c_0    anaconda
blas                      1.0                         mkl    anaconda
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.1.1                      0    anaconda
cairo                     1.14.12              h8948797_3    anaconda
certifi                   2020.4.5.1               py38_0    anaconda
curl                      7.69.1               h33f0ec9_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.9.1                h8a8886c_1    anaconda
gdk-pixbuf                2.28.2                        0    mw
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.56.2               hd408876_0    anaconda
graphite2                 1.3.13            he1b5a44_1001    conda-forge
graphviz                  2.38.0            hcf1ce16_1009    conda-forge
gtk2                      2.24.31                       0    mw
harfbuzz                  1.9.0             he243708_1001    conda-forge
icu                       58.2                 he6710b0_3    anaconda
igvtools                  2.5.3                         0    bioconda
intel-openmp              2020.1                      217    anaconda
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.17.1               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libcurl                   7.69.1               hf7181ac_0    conda-forge
libdb                     6.1.26                        0    bioconda
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.3                  he6710b0_1    anaconda
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgd                     2.2.5                h5400f36_4    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                hc3755c2_3    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   1.0.3                h1bed415_2    anaconda
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13                 h1bed415_1    anaconda
libxml2                   2.9.9                hea5a465_1    anaconda
libxslt                   1.1.32            hae48121_1003    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py38he904b0f_0    anaconda
mkl_fft                   1.0.15           py38ha843d7b_0    anaconda
mkl_random                1.1.0            py38h962f231_0    anaconda
ncurses                   6.2                  he6710b0_1  
numpy                     1.18.1           py38h4f9e942_0    anaconda
numpy-base                1.18.1           py38hde5b4d6_1    anaconda
openjdk                   11.0.1            h516909a_1016    conda-forge
openssl                   1.1.1g               h7b6447c_0    anaconda
pango                     1.40.14              he752989_2    conda-forge
pcre                      8.43                 he6710b0_0    anaconda
perl                      5.26.2               h14c3975_7    genomedk
perl-aceperl              1.92                    pl526_2    bioconda
perl-algorithm-munkres    0.08                    pl526_1    bioconda
perl-apache-test          1.40                    pl526_1    bioconda
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-appconfig            1.71                    pl526_1    bioconda
perl-array-compare        3.0.1                   pl526_1    bioconda
perl-autoloader           5.74                    pl526_2    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-bio-phylo            0.58                    pl526_2    bioconda
perl-bioperl              1.6.924                       4    bioconda
perl-bioperl-core         1.007002                pl526_2    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-cache-cache          1.08                    pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-cgi                  4.44            pl526h14c3975_1    bioconda
perl-class-inspector      1.34                    pl526_0    bioconda
perl-class-load           0.25                    pl526_0    bioconda
perl-class-load-xs        0.10            pl526h6bb024c_2    bioconda
perl-class-method-modifiers 2.12                    pl526_0    bioconda
perl-clone                0.42            pl526h516909a_0    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-convert-binary-c     0.78            pl526h6bb024c_3    bioconda
perl-convert-binhex       1.125                   pl526_1    bioconda
perl-crypt-rc4            2.02                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-data-optlist         0.110                   pl526_2    bioconda
perl-data-stag            0.14                    pl526_1    bioconda
perl-date-format          2.30                    pl526_2    bioconda
perl-db-file              1.852           pl526h14c3975_0    bioconda
perl-dbd-sqlite           1.64            pl526h516909a_0    bioconda
perl-dbi                  1.642                   pl526_0    bioconda
perl-devel-globaldestruction 0.14                    pl526_0    bioconda
perl-devel-overloadinfo   0.005                   pl526_0    bioconda
perl-devel-stacktrace     2.04                    pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-digest-perl-md5      1.9                     pl526_1    bioconda
perl-digest-sha1          2.13            pl526h6bb024c_1    bioconda
perl-dist-checkconflicts  0.11                    pl526_2    bioconda
perl-dynaloader           1.25                    pl526_1    bioconda
perl-email-date-format    1.005                   pl526_2    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-error                0.17027                 pl526_1    bioconda
perl-eval-closure         0.14            pl526h6bb024c_4    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-slurp-tiny      0.004                   pl526_1    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-file-which           1.23                    pl526_0    bioconda
perl-font-afm             1.20                    pl526_2    bioconda
perl-font-ttf             1.06                    pl526_0    bioconda
perl-gd                   2.71            pl526he860b03_0    bioconda
perl-getopt-long          2.50                    pl526_1    bioconda
perl-graph                0.9704                  pl526_1    bioconda
perl-graphviz             2.24            pl526h734ff71_0    bioconda
perl-html-element-extended 1.18                    pl526_1    bioconda
perl-html-entities-numbered 0.04                    pl526_1    bioconda
perl-html-formatter       2.16                    pl526_0    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tableextract    2.13                    pl526_2    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tidy            1.60                    pl526_0    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-html-treebuilder-xpath 0.14                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-image-info           1.38                    pl526_1    bioconda
perl-image-size           3.300                   pl526_2    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-sessiondata       1.03                    pl526_1    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-string            1.08                    pl526_3    bioconda
perl-io-stringy           2.111                   pl526_1    bioconda
perl-io-tty               1.12                    pl526_1    bioconda
perl-ipc-run              20180523.0              pl526_0    bioconda
perl-ipc-sharelite        0.17            pl526h6bb024c_1    bioconda
perl-jcode                2.07                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-lib                  0.63                    pl526_1    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-libxml-perl          0.08                    pl526_2    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-lwp-simple           6.15            pl526h470a237_4    bioconda
perl-mailtools            2.21                    pl526_0    bioconda
perl-math-cdf             0.1             pl526h14c3975_5    bioconda
perl-math-derivative      1.01                    pl526_0    bioconda
perl-math-random          0.72            pl526h14c3975_2    bioconda
perl-math-spline          0.02                    pl526_2    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mime-lite            3.030                   pl526_1    bioconda
perl-mime-tools           5.508                   pl526_1    bioconda
perl-mime-types           2.17                    pl526_0    bioconda
perl-mldbm                2.05                    pl526_1    bioconda
perl-module-implementation 0.09                    pl526_2    bioconda
perl-module-runtime       0.016                   pl526_1    bioconda
perl-module-runtime-conflicts 0.003                   pl526_0    bioconda
perl-moo                  2.003004                pl526_0    bioconda
perl-moose                2.2011          pl526hf484d3e_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-mro-compat           0.13                    pl526_0    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-ole-storage_lite     0.19                    pl526_3    bioconda
perl-package-deprecationmanager 0.17                    pl526_0    bioconda
perl-package-stash        0.38            pl526hf484d3e_1    bioconda
perl-package-stash-xs     0.28            pl526hf484d3e_1    bioconda
perl-params-util          1.07            pl526h6bb024c_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-parse-recdescent     1.967015                pl526_0    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-pdf-api2             2.035                   pl526_0    bioconda
perl-pod-escapes          1.07                    pl526_1    bioconda
perl-pod-usage            1.69                    pl526_1    bioconda
perl-postscript           0.06                    pl526_2    bioconda
perl-role-tiny            2.000008                pl526_0    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-set-scalar           1.29                    pl526_2    bioconda
perl-soap-lite            1.19                    pl526_1    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-sort-naturally       1.03                    pl526_2    bioconda
perl-spreadsheet-parseexcel 0.65                    pl526_2    bioconda
perl-spreadsheet-writeexcel 2.40                    pl526_2    bioconda
perl-statistics-descriptive 3.0702                  pl526_0    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-sub-exporter         0.987                   pl526_2    bioconda
perl-sub-exporter-progressive 0.001013                pl526_0    bioconda
perl-sub-identify         0.14            pl526h14c3975_0    bioconda
perl-sub-install          0.928                   pl526_2    bioconda
perl-sub-name             0.21                    pl526_1    bioconda
perl-sub-quote            2.006003                pl526_1    bioconda
perl-svg                  2.84                    pl526_0    bioconda
perl-svg-graph            0.02                    pl526_3    bioconda
perl-task-weaken          1.06                    pl526_0    bioconda
perl-template-toolkit     2.26                    pl526_1    bioconda
perl-test                 1.26                    pl526_1    bioconda
perl-test-harness         3.42                    pl526_0    bioconda
perl-test-leaktrace       0.16            pl526h14c3975_2    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-threaded             5.26.0                        0    bioconda
perl-tie-ixhash           1.23                    pl526_2    bioconda
perl-time-hires           1.9760          pl526h14c3975_1    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-timedate             2.30                    pl526_1    bioconda
perl-tree-dag_node        1.31                    pl526_0    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-type-tiny            1.004004                pl526_0    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-unicode-map          0.112           pl526h6bb024c_3    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-dom              1.46                    pl526_0    bioconda
perl-xml-dom-xpath        0.14                    pl526_1    bioconda
perl-xml-filter-buffertext 1.01                    pl526_2    bioconda
perl-xml-libxml           2.0132          pl526h7ec2d77_1    bioconda
perl-xml-libxslt          1.94                    pl526_1    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44            pl526h4e0c4b3_7    bioconda
perl-xml-regexp           0.04                    pl526_2    bioconda
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-sax-writer       0.57                    pl526_0    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xml-twig             3.52                    pl526_2    bioconda
perl-xml-writer           0.625                   pl526_2    bioconda
perl-xml-xpath            1.44                    pl526_0    bioconda
perl-xml-xpathengine      0.14                    pl526_2    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pip                       20.1               pyh9f0ad1d_0    conda-forge
pixman                    0.38.0               h7b6447c_0    anaconda
pypdftk                   0.4                      pypi_0    pypi
python                    3.8.2               hcff3b4d_14  
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  h7b6447c_0  
samtools                  1.7                           1    bioconda
setuptools                46.3.1           py38h32f6830_0    conda-forge
six                       1.14.0                   py38_0    anaconda
sqlite                    3.31.1               h62c20be_1  
tidyp                     1.04                          1    bioconda
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.2                h470a237_5    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h7b6447c_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h6597ccf_3    conda-forge

**content in genome dir**
-rwx------ 1 anksi anksi 1.2K May 19 20:24 bash_STAR.sh
-rw-rw-r-- 1 anksi anksi  763 May 19 20:25 bash_STAR.sh-8095368.out
-rw-rw-r-- 1 anksi anksi  763 May 19 20:25 bash_STAR.sh-9284369.out
-rw-rw-r-- 1 anksi anksi  716 May 19 20:24 chrLength.txt
-rw-rw-r-- 1 anksi anksi 2.0K May 19 20:25 chrNameLength.txt
-rw-rw-r-- 1 anksi anksi    0 May 19 20:24 chrNameLength.txt.fai
-rw-rw-r-- 1 anksi anksi 1.3K May 19 20:25 chrName.txt
-rw-rw-r-- 1 anksi anksi 1.4K May 19 20:25 chrStart.txt
-rwx------ 1 anksi anksi  84K May 19 20:25 ERCC92.fa
-rwx------ 1 anksi anksi 8.0K May 19 20:25 ERCC92.gtf
-rw-rw-r-- 1 anksi anksi  16M May 19 20:25 exonGeTrInfo.tab
-rw-rw-r-- 1 anksi anksi 6.9M May 19 20:25 exonInfo.tab
-rw-rw-r-- 1 anksi anksi 1.6M May 19 20:25 geneInfo.tab
-rw-rw-r-- 1 anksi anksi 2.7G May 19 20:28 Genome
-rw-rw-r-- 1 anksi anksi  833 May 19 20:28 genomeParameters.txt
-rw-rw-r-- 1 anksi anksi  439 May 19 20:28 gtf2bed.sh
-rw-rw-r-- 1 anksi anksi    0 May 19 20:25 gtf2bed.sh-8421478.out
-rw-rw-r-- 1 anksi anksi  30K May 19 20:25 Log.out
-rw-rw-r-- 1 anksi anksi 225M May 19 20:25 mm9_20bin_chr1.bed
-rw-rw-r-- 1 anksi anksi 3.1G May 19 20:28 mm9_20_win.bed
-rwx------ 1 anksi anksi  71K May 19 20:28 mm9-blacklist.bed
-rw-rw-r-- 1 anksi anksi 2.6G May 19 20:25 mm9_ERCC92.fa
-rwxrwxr-x 1 anksi anksi 2.6G May 19 20:28 mm9.fa
-rw-rw-r-- 1 anksi anksi 1.2K May 19 20:28 mm9.fa.fai
-rwx------ 1 anksi anksi  41K May 19 20:28 mm9_genePrid.txt
-rw-rw-r-- 1 anksi anksi 173M May 19 20:25 mm9.knownGene.bed
-rw-rw-r-- 1 anksi anksi 164M May 19 20:24 mm9.knownGene.ERCC92.gtf
-rw-rw-r-- 1 anksi anksi  12M May 19 20:25 mm9.knownGene.genePred
-rw-rw-r-- 1 anksi anksi 7.5M May 19 20:28 mm9.knownGene.genePred.bed
-rw-rw-r-- 1 anksi anksi 164M May 19 20:24 mm9.knownGene.gtf
drwxrwxr-x 2 anksi anksi    1 May 19 20:25 preparsed
-rw-rw-r-- 1 anksi anksi  21G May 19 20:27 SA
-rw-rw-r-- 1 anksi anksi 374K May 19 20:24 SAindex
-rw-rw-r-- 1 anksi anksi 6.0M May 19 20:25 sjdbInfo.txt
-rw-rw-r-- 1 anksi anksi 7.4M May 19 20:25 sjdbList.fromGTF.out.tab
-rw-rw-r-- 1 anksi anksi 5.4M May 19 20:25 sjdbList.out.tab
-rw-rw-r-- 1 anksi anksi 3.2M May 19 20:28 transcriptInfo.tab
-rw-rw-r-- 1 anksi anksi  134 May 19 20:25 windmak.sh

**Comment by olarerin** [comment]
Hey Anksi

1) Can you list the contents of your genome directory (mouse/)? 
2) Where did you obtain the fasta files in your mouse/ directory?  Remember, you need a single fasta file per chromosome.
3) Can you output the first few lines from your genePred file?
3) Lastly, have you been able to successfully run MetaPlotR using the example in the tutorial?  If so, then there is probably not a dependency issue.  If not, were in the pipeline did it fail?

**Comment by anksi** [comment]
Thanks for your prompt response.
1. I have already provided the details of my /mouse (mm9, genome folder) in the above post. Look at the section "content in genome dir",
2. I have downloaded them from UCSC FTP and it works fine for various other analysis, though I should admit that I had entire genome in one file (mm9.fa) when I tried it for the first time but even after downloading all of the individual chromosome files, it doesn't work, 
3. Yes, PFA output from genePred below,
4. I haven't tried it yet 

**mm9.genePred**
#name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonEnds	proteinID	alignID
uc007aet.1	chr1	-	3195984	3205713	3195984	3195984	2	3195984,3203519,	3197398,3205713,		uc007aet.1
uc007aeu.1	chr1	-	3204562	3661579	3206102	3661429	3	3204562,3411782,3660632,	3207049,3411982,3661579,	Q5GH67	uc007aeu.1
uc007aev.1	chr1	-	3638391	3648985	3638391	3638391	2	3638391,3648927,	3640590,3648985,		uc007aev.1
uc007aew.1	chr1	-	4280926	4399322	4283061	4399268	4	4280926,4341990,4342282,4399250,	4283093,4342162,4342918,4399322,	NP_001182591	uc007aew.1
uc007aex.2	chr1	-	4333587	4350395	4334680	4342906	4	4333587,4341990,4342282,4350280,	4340172,4342162,4342918,4350395,	Q548Q8	uc007aex.2
uc007aey.1	chr1	-	4481008	4483816	4481796	4483487	2	4481008,4483180,	4482749,4483816,	Q61473	uc007aey.1
uc007aez.1	chr1	-	4481008	4486494	4481796	4483487	5	4481008,4483180,4483852,4485216,4486371,	4482749,4483547,4483944,4486023,4486494,	Q61473	uc007aez.1
uc007afa.1	chr1	-	4481008	4486494	4481796	4485236	4	4481008,4483852,4485216,4486371,	4482749,4483944,4486023,4486494,	Q61473	uc007afa.1
uc007afb.1	chr1	-	4481008	4486494	4481796	4482672	3	4481008,4483852,4486371,	4482749,4483944,4486494,	Q61473-2	uc007afb.1

**Comment by olarerin** [comment]
Oh I see.  Well the genome directory should ONLY contain your genome of interest, each chromosome as a separate file.  Please see the tutorial and try running the example first -- i think it'll really help with understanding how the pipeline works and the format of files/directories that it expects.

**Comment by anksi** [comment]
Hi again,

I have tried replicating the source code. For annotating the genome using, make_annot_bed.pl which is been used taking hg19_gencode.genePred file and it worked perfectly fine but it gives error when it has been used on the mouse genome.

It seems something is wrong with "Gene and gene prediction table" of the mouse that I have downloaded from the UCSC browser. I have used UCSC genes under track section since for mouse genome, UCSC does not have Genecode v2 version! Can you suggest, what can I use under track section so as to annotate mouse genome successfully?

Thanks for your help in advance.
Best 
Ankita

**Comment by anksi** [comment]
Hi,
I have managed to resolve the issue.

Best
Ankita
